apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: proteus-node-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proteus-node-agent
subjects:
  - kind: ServiceAccount
    name: proteus-node-agent
    namespace: proteus-system
