apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proteus-system

resources:
  - ns.yaml
  - sa.yaml
  - sa-agent.yaml
  - clusterrole.yaml
  - clusterrole-agent.yaml
  - clusterrole-mover.yaml
  - clusterrolebinding.yaml
  - clusterrolebinding-agent.yaml
  - deploy.yaml
  - daemonset.yaml
  - svc.yaml
  - ../crds

labels:
  - pairs:
      app.kubernetes.io/name: proteus
      app.kubernetes.io/part-of: proteus
    includeSelectors: true
